server:
  address: 127.0.0.1
  port: 8080

jwtToken:
  secret: your secret
#  timeout: 1800000
  timeout: 180000000
  algorithm: HS512

#your datasouce config
source:
  initial-size: 2
  min-idle: 1
  max-wait: 60000
  max-active: 10

spring:
  mvc:
    async:
      request-timeout: 30s

#  davinci datasouce config
  datasource:
    url: jdbc:mysql://localhost:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    url: jdbc:mysql://10.143.131.33:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    min-idle: 1
    max-wait: 60000
    max-active: 10

  redis:

    isEnable: false
#    standalone
    host: 127.0.0.1
    port: 6379

#     cluster
#    cluster:
#          nodes:

    password:
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

  mail:
    host: email.creditease.cn
    port: 25
    username: it.edp.support@creditease.cn
    password: edp#fasong963
    nickname: Davinci

    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: false

phantomjs_home: /usr/local/bin/phantomjs

logging:
  level:
    edp:
      davinci:
        dao: debug
