#  <<
#  Davinci
#  ==
#  Copyright (C) 2016 - 2018 EDP
#  ==
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#        http://www.apache.org/licenses/LICENSE-2.0
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#  >>



server:
  address: 127.0.0.1
  port: 8080

jwtToken:
  secret: your secret
  timeout: 180000000
#  timeout: 1800000
  algorithm: HS512

#your datasouce config
source:
  initial-size: 2
  min-idle: 1
  max-wait: 60000
  max-active: 10

spring:
  mvc:
    async:
      request-timeout: 30s

  # davinci datasouce config
  datasource:
    url: jdbc:mysql://localhost:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    min-idle: 1
    max-wait: 60000
    max-active: 10

  redis:

    isEnable: false
    # standalone config
    host: 127.0.0.1
    port: 6379

  #  cluster config
  #  cluster:
  #       nodes:

    password:
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

  mail:
    host: email.creditease.cn
    port: 25
    username: it.edp.support@creditease.cn
    password: edp#fasong963
    nickname: Davinci

    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: false

phantomjs_home: /usr/local/bin/phantomjs

logging:
  level:
    edp:
      davinci:
        dao: debug
